version: '2.1'
services:
  ambassador:
    build:
      context: .
      dockerfile: ./cmd/ambassador/Dockerfile
    environment:
      AMBASSADOR: "http://127.0.0.1:8000"
      APPLICATION: "http://application:8080"
      AWS_PROFILE: "${AWS_PROFILE}"
      AWS_REGION: "${AWS_REGION}"
      DEBUG: "yes"
      HOME: "/home"
      QUEUE: "${QUEUE}"
    expose:
      - "8000"
    links:
      - application
    ports:
      - "8000:8000"
    volumes:
      - $HOME/.aws/:/home/.aws/
  runner:
    build:
      context: .
      dockerfile: ./cmd/runner/Dockerfile
    environment:
      InitializationCallbackUrl: "http://ambassador:8000/runner-callback"
      Runner__LogLevel: "1"
      Runner__CountThreads: "4"
    expose:
      - "8080"
    ports:
      - "8080:80"
  application:
    build:
      context: .
      dockerfile: ./cmd/application/Dockerfile
    environment:
      AMBASSADOR: "http://ambassador:8000"
      APPLICATION: "http://127.0.0.1:4000"
      DEBUG: "yes"
    expose:
      - "4000"
    ports:
      - "4000:4000"
